[AA-1465] Add Applications API endpoint to Admin API
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp pull request #288
Opened 2022-06-17 22:36 UTC by CSR2017

@andonyns 
Please help review and merge the changes. 
Thanks

2022-06-27 21:11 UTC, pmcvtm requested changes
This is mostly functional but we have a few important things to do before we merge:

- add e2e tests for new endpoints
- fix missing 404 responses
- fix up resource groupings and URLs
- explain or revert behavior changes in `Edit` command
- fix new build warnings

Please take a look at the other comments as well. We'll plan to address Swagger / documentation changes in another PR.

2022-07-01 01:04 UTC, pmcvtm commented on Application/EdFi.Ods.Admin.Api/Infrastructure/AutoMapper/AdminApiMappingProfile.cs
> +                .ForMember(dst => dst.ProfileName, opt => opt.MapFrom(src => src.ProfileName()));
This answer here is _no_, or at least not easily! The `Application` class is in a different repo.

2022-07-01 01:17 UTC, pmcvtm commented
I've addressed most of the feedback here, with the exception of Swagger changes we'll look at separately, and the missing e2e tests which I am still working on. @saa14 please give the code changes a look over. Thanks!

2022-07-01 14:39 UTC, saa14 approved these changes

2022-07-01 15:10 UTC, pmcvtm approved these changes
Should have re-approved with my other comment - LGTM, obviously.

We will merge this and open a second PR with new tests + repeatable patterns for the E2E Postman tests.

2022-07-01 15:10 UTC, merged