[AA-1676] Deleted Learning Standard Functionality
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp pull request #399
Opened 2023-05-15 17:12 UTC by kledezmagap

Deleted Learning Standard Functionality

2023-05-15 17:21 UTC, CSR2017 requested changes

2023-05-15 17:38 UTC, kledezmagap commented on Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
> +  <ItemGroup>
I did not modify the csproj, I'm not really sure why Its there.
Just in case I'm gonna remove it.

2023-05-15 17:42 UTC, kledezmagap commented on Application/EdFi.Ods.AdminApp.Management/OdsSecretConfiguration.cs
>          public ABProxyApiCredential ProductionAcademicBenchmarkApiClientKeyAndSecret { get; set; }
Done

2023-05-17 14:25 UTC, CSR2017 requested changes

2023-05-17 15:20 UTC, CSR2017 commented on Application/EdFi.Ods.AdminApp.Web/Controllers/SetupController.cs
> -        public async Task<JsonResult> CompleteFirstTimeSetup()
@kledezmagap 
Why are removing entire controller action ? It is needed action. We have to just remove the Hangfire related code !!

2023-05-19 12:00 UTC, CSR2017 approved these changes

2023-05-19 14:29 UTC, merged