[AA-1737] Update Admin App to .NET 8
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp pull request #453
Opened 2024-03-26 16:22 UTC by jleiva-gap

- Upgrade project to NET 8
- Upgrade nugets
- Upgrade Ed-Fi packages
- Update EF code to apply changes added to EF Core 8
- Fix tests

2024-03-27 17:39 UTC, DavidJGapCR commented on Application/EdFi.Ods.AdminApp.Management.Tests/MockExtensions.cs
> +//using System.Data.Entity;
Can we remove these lines?

2024-03-27 17:44 UTC, DavidJGapCR commented on Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/CopyClaimSetCommandV6Service.cs
> +//using System.Data.Entity;
Same here

2024-04-01 22:11 UTC, jagudelo-gap requested changes

2024-04-01 22:11 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/CopyClaimSetCommandV53Service.cs
> +//using System.Data.Entity;
Remove line

2024-04-01 22:11 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApp.Management/IFirstTimeSetupService.cs
> +            /*var existingApplication = await UsersContext.Applications.AsEnumerable().FirstOrDefaultAsync(x =>
Remove comment out lines

2024-04-01 22:11 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApp.Web/Startup.cs
> +// using EdFi.Admin.DataAccess.DbConfigurations;
remove line

2024-04-01 22:11 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApp.Management.Tests/TestDbAsyncEnumerator.cs
> +            return  GetAsyncEnumerator(cancellationToken);  //new TestDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
remove comment out line

2024-04-01 22:35 UTC, jagudelo-gap approved these changes

2024-04-01 22:38 UTC, merged